Rack one
Archyfly/rack2 pull request #1
Opened 2019-12-24 16:34 UTC by Archyfly

проверьте пожалуйста, правильно ли понял.

2020-01-11 22:05 UTC, BubuntuClu requested changes

2020-01-11 22:05 UTC, BubuntuClu commented on app.rb
> +      return [400, headers, ['Incorrect input format']]
в ответе должны быть указаны конкретные неверные форматы

2020-01-11 22:05 UTC, BubuntuClu commented on app.rb
> +      return [404, headers, ["Not found, #{path}, #{request}, #{request.params}"]]
сделай метод для отправки ответа. используй объект класса `Rack::Response`. в этот метод просто передавай код ошибки и текст

2020-01-11 22:05 UTC, BubuntuClu commented on middleware/TimeFormatter.rb
> +  def valid_format(val)
`def valid_format?` тогда, раз у тебя ответ true/false

2020-01-11 22:05 UTC, BubuntuClu commented on middleware/TimeFormatter.rb
> +  def format(params)
сделай через стандартный класс с инициализацией. массив ошибок, массив параметров. метод call, все рассортирует. и потом через вспомогательные методы типа `valid?` определяй все ли корректно распозналось

2020-01-11 22:05 UTC, BubuntuClu commented on middleware/TimeFormatter.rb
> +      params.each { |key, value|
что-то много `each`ей получилось.

2020-01-11 22:05 UTC, BubuntuClu commented on app.rb
> +    rescue FormatError
на мой взгляд обработка через рескью, не совсем хороша. обработай этот случай своими силами, а не ловлей ошибки. ты же знаешь что у тебя могут быть плохие форматы. ты их обрабатываешь и выводишь специально

2020-01-12 03:22 UTC, Archyfly commented on middleware/TimeFormatter.rb
> +  def valid_format(val)
ok

2020-01-12 03:24 UTC, merged